//Generated By AsyPadv1.1
import olympiad;
import markers;
import math;
import graph;
//change the unit size to fit your needs
unitsize(1cm);
//dependency level 0
/* You can change the coordinates of these points of dependency level 0.
The drawing will retain the same relationships and qualities.
Please be aware that as a result of this some of the image may be clipped off. */
pair O = (3.91, 17.09); dot(O); label("$O$", O, dir(315.0));
pair A = (5.11, 17.34); dot(A); label("$A$", A, dir(6.788974574439635));
//dependency level 1
//Do not change anything below, unless you are experienced in Asymptote.
path circO_A = Circle(O, abs(O-A)); draw(circO_A);
//dependency level 2
pair B = relpoint(circO_A, -0.7215088337730656); dot(B); label("$B$", B, dir(95.14219519526551));
pair D = relpoint(circO_A, -0.15943168564932905); dot(D); label("$D$", D, dir(315.0));
//dependency level 3
path segO_B = O--B; 
path segO_D = O--D; 
path lineA_D = (A-20.0*unit(D-A))--(D+20.0*unit(D-A)); draw(lineA_D);
//dependency level 4
path perB_segO_B = (B-20.0*(dir(segO_B).y, -dir(segO_B).x))--(B+20.0*(dir(segO_B).y, -dir(segO_B).x)); draw(perB_segO_B);
path perD_segO_D = (D-20.0*(dir(segO_D).y, -dir(segO_D).x))--(D+20.0*(dir(segO_D).y, -dir(segO_D).x)); draw(perD_segO_D);
//dependency level 5
pair P = intersectionpoint(perB_segO_B, perD_segO_D); dot(P); label("$P$", P, dir(315.0));
//dependency level 6
path lineP_A = (P-20.0*unit(A-P))--(A+20.0*unit(A-P)); 
//dependency level 7
pair C = intersectionpoints(lineP_A, circO_A)[1]; dot(C); label("$C$", C, dir(219.16249447468377));
//dependency level 8
path segO_C = O--C; 
//dependency level 9
path perC_segO_C = (C-20.0*(dir(segO_C).y, -dir(segO_C).x))--(C+20.0*(dir(segO_C).y, -dir(segO_C).x)); draw(perC_segO_C);
//dependency level 10
pair Q = intersectionpoint(perD_segO_D, perC_segO_C); dot(Q); label("$Q$", Q, dir(260.09609148227105));
pair R = intersectionpoint(perC_segO_C, lineA_D); dot(R); label("$R$", R, dir(6.30050443438347));
//dependency level 11
path segA_Q = A--Q; draw(segA_Q);
path segB_R = B--R; draw(segB_R);
//dependency level 12
pair E = intersectionpoints(segA_Q, circO_A)[1]; dot(E); label("$E$", E, dir(129.81950808569363));
//clip the drawing view
clip((0.0, 13.22)--(0.0, 20.0)--(10.0, 20.0)--(10.0, 13.22)--cycle);